version: "3.4"
services:
  tms_auth_db:
    restart: always
    image: postgres:latest
    volumes:
      - tms_auth_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tms_auth
  tms_auth:
    build: .
    command: npm run start:prod
    depends_on:
      - tms_auth_db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
volumes:
  tms_auth_volume:
