version: "3.4"
services:
  tms_auth:
    restart: always
    image: postgres:latest
    volumes:
      - tms_auth_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  tms_main:
    restart: always
    image: postgres:latest
    volumes:
      - tms_main_volume:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
volumes:
  tms_auth_volume:
  tms_main_volume:
